generator:
  class: tmcTwitterBootstrapDoctrineGenerator
  param:
    model_class:           MoneyLog
    theme:                 tmcTwitterBootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          doanh_thu_ngay
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Doanh thu theo ng√†y
        display: [created_date, sum_money]
        actions: {}
        object_actions: {}
      filter:
        class: gvManageDoanhThuNgayFormFiltersAdmin
        display: [created_at, partner_id, game_id]
      form:    ~
      edit:    ~
      new:     ~
